version: "3"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: contests
    ports:
      - "27017:27017"

  db:
    image: postgres
    networks:
      - nodenet
    environment:
      POSTGRES_DB: contests

  web:
    image: name-contests-api
    ports:
      - "3000:3000"
    networks:
      - nodenet
    environment:
      DB_HOST: db
      MONGODB_HOST: mongodb
    #command: ["./wait.sh", "db:5432", "--", "lib", "index.js"]

  # server:
  #   image: nginx:1.14.2-alpine
  #   restart: always
  #   volumes:
  #     - ./public_html:/public_html
  #     - ./conf.d:/etc/nginx/conf.d/
  #     - ./dhparam:/etc/nginx/dhparam
  #     - ./certbot/conf/:/etc/nginx/ssl/
  #     - ./certbot/data:/usr/share/nginx/html/letsencrypt
  #   ports:
  #     - 80:80
  #     - 443:443
  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email rio@dimasrio.com --agree-tos --no-eff-email -d centz.dimasrio.com
  #   volumes:
  #     - ./certbot/conf/:/etc/letsencrypt
  #     - ./certbot/logs/:/var/log/letsencrypt
  #     - ./certbot/data:/usr/share/nginx/html/letsencrypt

networks:
  nodenet:
